<a href="https://colab.research.google.com/github/EbrahimBenBella/Data-science-final-project/blob/main/lab1_10_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install torch torchvision --quiet

import torch
import torchvision
import numpy as np

print("PyTorch version:", torch.__version__)

PyTorch version: 2.6.0+cu124


In [3]:
# Create tensors from a Python list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print("Tensor from list:\n", x_data)

Tensor from list:
 tensor([[1, 2],
        [3, 4]])


In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print("\nTensor from NumPy:\n", x_np)


Tensor from NumPy:
 tensor([[1, 2],
        [3, 4]])


In [5]:
x_ones = torch.ones((2, 3))
x_zeros = torch.zeros((2, 3))
x_rand = torch.rand((2, 3))
print("\nOnes:\n", x_ones)
print("\nZeros:\n", x_zeros)
print("\nRandom:\n", x_rand)


Ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Random:
 tensor([[0.9723, 0.9195, 0.4114],
        [0.7489, 0.3483, 0.3004]])


In [6]:
print("\n--- Tensor Operations ---")
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print("X:\n", x)
print("Y:\n", y)


--- Tensor Operations ---
X:
 tensor([[0.2291, 0.2673],
        [0.3487, 0.4348]])
Y:
 tensor([[0.6714, 0.1010],
        [0.3861, 0.1133]])


In [7]:
# Addition
z = x + y
print("\nX + Y:\n", z)


X + Y:
 tensor([[0.9005, 0.3682],
        [0.7348, 0.5481]])


In [ ]:
# Matrix multiplication
z2 = torch.mm(x, y)
print("\nMatrix Multiplication X @ Y:\n", z2)

In [ ]:
# Element-wise multiplication
z3 = x * y
print("\nElement-wise Multiplication X * Y:\n", z3)